default_leagues:
  - Big 5 European Leagues Combined

league_mappings:
  Premier League: ENG-Premier League
  England/Premier League: ENG-Premier League
  English Premier League: ENG-Premier League
  English football league system: ENG-Premier League

  LaLiga: ESP-La Liga
  Spain/La Liga: ESP-La Liga
  Spanish football league system: ESP-La Liga

  Ligue 1: FRA-Ligue 1
  Ligue 1 / French football league system: FRA-Ligue 1
  France/Ligue 1: FRA-Ligue 1

  Serie A: ITA-Serie A
  Italy/Serie A: ITA-Serie A

  Bundesliga: GER-Bundesliga
  Germany/Bundesliga: GER-Bundesliga

  Primeira Liga: POR-Primeira Liga
  Portugal/Primeira Liga: POR-Primeira Liga

  Belgian Pro League: BEL-Pro League
  Belgium/Belgian Pro League: BEL-Pro League

  Eredivisie: NED-Eredivisie
  Eredivisie / Dutch football league system: NED-Eredivisie
  Netherlands/Eredivisie: NED-Eredivisie

  Liga MX: MEX-Liga MX
  Mexico/Liga MX: MEX-Liga MX

  Major League Soccer: USA-MLS
  USA/MLS: USA-MLS
  MLS: USA-MLS

  Brazilian football league system: BRA-Serie A
  Campeonato Brasileiro Serie A: BRA-Serie A
  Brazil/Serie A: BRA-Serie A

  Argentina Primera Division: ARG-Primera Division
  Argentine Primera Division: ARG-Primera Division
  Argentina/Primera Division: ARG-Primera Division

  Saudi Pro League: KSA-Saudi Pro League
  Saudi Arabia/Saudi Pro League: KSA-Saudi Pro League

  Turkish Super Lig: TUR-Super Lig
  Turkey/Super Lig: TUR-Super Lig
  Turkish Süper Lig: TUR-Super Lig
  Turkey/Süper Lig: TUR-Super Lig

  Scottish Premiership: SCO-Premiership
  Scotland/Scottish Premiership: SCO-Premiership

maybe_supported_leagues:
  Czech First League: CZE-First League
  Danish Superliga: DEN-Superliga
  Egyptian Premier League: EGY-Premier League
  Iran Persian Gulf Pro League: IRN-Persian Gulf Pro League
  New Zealand National League: NZL-National League
  Qatar Stars League: QAT-Stars League
  Russian Premier League: RUS-Premier League
  South African Premier Division: RSA-Premier Division
  UAE Pro League: UAE-Pro League
  Uzbekistan Super League: UZB-Super League
