player_aliases:
  Cristiano Ronaldo dos Santos Aveiro:
    - Cristiano Ronaldo
    - Cristiano Ronaldo dos Santos Aveiro
  Kylian Mbappé Lottin:
    - Kylian Mbappé
    - Kylian Mbappe
    - Kylian Mbappé Lottin
  Lionel Andrés Messi Cuccittini:
    - Lionel Messi
    - Lionel Andres Messi
    - Lionel Andrés Messi Cuccittini
  Neymar da Silva Santos Junior:
    - Neymar
    - Neymar Jr
    - Neymar da Silva Santos Junior
  Riyad Mahrez:
    - Riyad Mahrez
